root = "/app"
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main cmd/main/main.go"
entrypoint = "./tmp/main"
bin = "./tmp/main"
dir = "."
include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
exclude_dir = ["tmp", "vendor", "node_modules", ".git"]

[log]
time = true
