// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	SessionToken string
	UserID       int64
	CreatedAt    pgtype.Timestamptz
	CsrfToken    string
}

type AuthUser struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Profile struct {
	UserID    int64
	Firstname pgtype.Text
	Surname   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RolePermission struct {
	WorkspaceID int64
	Role        string
	Permission  string
}

type Routemap struct {
	ID          int64
	Path        string
	Destination string
	CreatedAt   pgtype.Timestamptz
	WorkspaceID int64
}

type Workspace struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WorkspaceMember struct {
	WorkspaceID int64
	ProfileID   int64
	Role        string
	CreatedAt   pgtype.Timestamptz
}
