// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	SessionToken string
	UserID       pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	CsrfToken    string
}

type AuthUser struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Profile struct {
	UserID    pgtype.UUID
	Firstname pgtype.Text
	Surname   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RolePermission struct {
	WorkspaceID pgtype.UUID
	Role        string
	Permission  string
}

type Routemap struct {
	ID          int64
	Path        pgtype.Text
	Destination string
	CreatedAt   pgtype.Timestamptz
	WorkspaceID pgtype.UUID
}

type Workspace struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID
	ProfileID   pgtype.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
}
