// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO auth.session (user_id, session_token, csrf_token)
VALUES ($1, $2, $3)
`

type CreateAuthSessionParams struct {
	UserID       pgtype.UUID
	SessionToken string
	CsrfToken    string
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createAuthSession, arg.UserID, arg.SessionToken, arg.CsrfToken)
	return err
}

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO auth.users (id, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, created_at, updated_at
`

type CreateAuthUserParams struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createAuthUser, arg.ID, arg.Email, arg.PasswordHash)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO public.profile (user_id, firstname, surname)
VALUES ($1, $2, $3)
RETURNING user_id, firstname, surname, created_at, updated_at
`

type CreateProfileParams struct {
	UserID    pgtype.UUID
	Firstname pgtype.Text
	Surname   pgtype.Text
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.UserID, arg.Firstname, arg.Surname)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.Firstname,
		&i.Surname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRolePermission = `-- name: CreateRolePermission :exec
INSERT INTO public.role_permission (workspace_id, role, permission)
VALUES ($1, $2, $3)
`

type CreateRolePermissionParams struct {
	WorkspaceID pgtype.UUID
	Role        string
	Permission  string
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) error {
	_, err := q.db.Exec(ctx, createRolePermission, arg.WorkspaceID, arg.Role, arg.Permission)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO public.workspace (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateWorkspace(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceMember = `-- name: CreateWorkspaceMember :exec
INSERT INTO public.workspace_member (workspace_id, profile_id, role)
VALUES ($1, $2, $3)
`

type CreateWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID
	ProfileID   pgtype.UUID
	Role        string
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, createWorkspaceMember, arg.WorkspaceID, arg.ProfileID, arg.Role)
	return err
}

const getAllRoutemaps = `-- name: GetAllRoutemaps :many
SELECT id, path, destination, created_at, workspace_id FROM public.routemap
`

func (q *Queries) GetAllRoutemaps(ctx context.Context) ([]Routemap, error) {
	rows, err := q.db.Query(ctx, getAllRoutemaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routemap
	for rows.Next() {
		var i Routemap
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Destination,
			&i.CreatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthSessionByToken = `-- name: GetAuthSessionByToken :one
SELECT session_token, user_id, csrf_token, created_at
FROM auth.session
WHERE session_token = $1
LIMIT 1
`

type GetAuthSessionByTokenRow struct {
	SessionToken string
	UserID       pgtype.UUID
	CsrfToken    string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetAuthSessionByToken(ctx context.Context, sessionToken string) (GetAuthSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByToken, sessionToken)
	var i GetAuthSessionByTokenRow
	err := row.Scan(
		&i.SessionToken,
		&i.UserID,
		&i.CsrfToken,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one
SELECT id, email, password_hash, created_at, updated_at
FROM auth.users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetAuthUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoutemap = `-- name: GetRoutemap :one
SELECT id, path, destination, workspace_id, created_at
FROM public.routemap
WHERE path = $1
LIMIT 1
`

type GetRoutemapRow struct {
	ID          int64
	Path        pgtype.Text
	Destination string
	WorkspaceID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetRoutemap(ctx context.Context, path pgtype.Text) (GetRoutemapRow, error) {
	row := q.db.QueryRow(ctx, getRoutemap, path)
	var i GetRoutemapRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Destination,
		&i.WorkspaceID,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByProfile = `-- name: GetWorkspaceByProfile :one
SELECT w.id, w.name, w.created_at, w.updated_at
FROM public.workspace w
JOIN public.workspace_member wm ON wm.workspace_id = w.id
WHERE wm.profile_id = $1
ORDER BY w.created_at
LIMIT 1
`

func (q *Queries) GetWorkspaceByProfile(ctx context.Context, profileID pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByProfile, profileID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRoutemap = `-- name: InsertRoutemap :exec
INSERT INTO public.routemap (destination, workspace_id)
VALUES ($1, $2)
`

type InsertRoutemapParams struct {
	Destination string
	WorkspaceID pgtype.UUID
}

func (q *Queries) InsertRoutemap(ctx context.Context, arg InsertRoutemapParams) error {
	_, err := q.db.Exec(ctx, insertRoutemap, arg.Destination, arg.WorkspaceID)
	return err
}

const updateRoutemapDestination = `-- name: UpdateRoutemapDestination :exec
UPDATE public.routemap
SET destination = $2
WHERE id = $1
`

type UpdateRoutemapDestinationParams struct {
	ID          int64
	Destination string
}

func (q *Queries) UpdateRoutemapDestination(ctx context.Context, arg UpdateRoutemapDestinationParams) error {
	_, err := q.db.Exec(ctx, updateRoutemapDestination, arg.ID, arg.Destination)
	return err
}
