// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
)

const getAllRouteMaps = `-- name: GetAllRouteMaps :many
SELECT id, path, destination, created_at FROM public.routemap
`

func (q *Queries) GetAllRouteMaps(ctx context.Context) ([]Routemap, error) {
	rows, err := q.db.QueryContext(ctx, getAllRouteMaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routemap
	for rows.Next() {
		var i Routemap
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Destination,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
